---
title: "Assignment 1: R markdown and leaflet "
author: ""
date: "16 Januar 2017"
output: html_document
---
#Unemployment rate of the federal states of germany
```{r, echo=FALSE, results='hide', warning=FALSE,message=FALSE}
library(leaflet)
library(sp)
library(RColorBrewer)
library(raster)
library(plyr)
library(dplyr)
adm <- getData('GADM', country='DEU', level=1)
test_data<-data.frame(ID_1=(1:16), N=c(3.8,3.6,10.7,8.7,10.9,7.9,5.5,10.4,6.1,8.0,5.2,7.2,10.2,8.2,6.5,7.4))
joined<-sp::merge(adm, test_data, by.x="ID_1")
pal <- colorNumeric(
        palette = "YlGnBu",
        domain = joined$N)
```

```{r, echo=FALSE}
leaflet() %>%addTiles(urlTemplate = 'http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png',
                         attribution = 'Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
)%>%
        addPolygons(data=joined,stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.7,
                    color = ~pal(N))%>%
        addLegend("bottomright", pal = pal, values = joined$N,
                  title = "unemployment rate",
                  labFormat = labelFormat(suffix = "%"),
                  opacity = 1) 
```                  